<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "scextensionkey"
 *
 * Auto generated by Extension Builder 2019-06-15
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'sctitle',
    'description' => 'scdesciription',
    'category' => 'plugin',
    'author' => 'Sebastian Christoph',
    'author_email' => 'admin@sebastian-christoph.de',
    'state' => 'alpha',
    'uploadfolder' => 0,
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '1.0.0',
    'constraints' => [
        'depends' => [
            'typo3' => '9.5.0-9.5.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
